### PR TITLE
Delete focal/.releasepy_NO_ARCH_ARMHF

### PR DESCRIPTION
**Pull request by scpeters**
armhf builds are working now, so allow them to be triggered by release.py

### CODE REVIEW

**Comment by scpeters** [comment]
well apparently they aren't working

[Build Status](https://build.osrfoundation.org/job/ign-rendering3-debbuilder/84/) https://build.osrfoundation.org/job/ign-rendering3-debbuilder/84/

~~~
Investigating (0) ignition-rendering3-build-deps:armhf < 3.6.0-1~bionic @iU mK Nb Ib >
Broken ignition-rendering3-build-deps:armhf Depends on libogre-2.1-dev:armhf < none @un H >
  Removing ignition-rendering3-build-deps:armhf because I can't find libogre-2.1-dev:armhf
~~~

**Comment by scpeters** [comment]
> well apparently they aren't working
> 
> [Build Status](https://build.osrfoundation.org/job/ign-rendering3-debbuilder/84/) https://build.osrfoundation.org/job/ign-rendering3-debbuilder/84/
> 
> ```
> Investigating (0) ignition-rendering3-build-deps:armhf < 3.6.0-1~bionic @iU mK Nb Ib >
> Broken ignition-rendering3-build-deps:armhf Depends on libogre-2.1-dev:armhf < none @un H >
>   Removing ignition-rendering3-build-deps:armhf because I can't find libogre-2.1-dev:armhf
> ```

I guess it's just a problem with bionic; it works for focal and buster

**Comment by scpeters** [comment]
there were also `.releasepy_NO_ARCH_ARMHF` files in `focal` and `bionic` folders. So I've removed the `focal` file in https://github.com/ignition-release/ign-rendering3-release/pull/4/commits/8ff9f5d3ff9117b492f02fdcc043ca6ea72b8fcf and retained the `bionic` file until we can fix it. I think this is ready for review

**Comment by scpeters** [comment]
ping @j-rivero @chapulina

**Comment by j-rivero** [comment]
> ping @j-rivero @chapulina

we did not release `ogre-2.1` on Bionic/armhf. Let put the buildfarm to work: [Build Status](https://build.osrfoundation.org/job/ogre-2.1-debbuilder/52/)

**Comment by chapulina** [comment]
> Let put the buildfarm to work: Build Status

Failed :cry:

**Comment by scpeters** [comment]
we can merge this now to enable focal armhf builds and try to fix bionic armhf at a later time

**Review by chapulina — APPROVED** [review]

**Pull request merged**
